# Generated by Django 5.1.6 on 2026-10-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_intelligence', '0001_initial'),
        ('listings', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credibilityscore',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='listings.listing'),
        ),
    ]
